// Generated by scripts/build.mjs; edit src/client/** instead.
window.__ModuleLoader__.load({
  id: "dsh-drag-file",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.ts
var index_exports = {};
__export(index_exports, {
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(index_exports);

// src/protocol.ts
var FILE_DROP_ROUTE = "/file-drop";
var RESOLVE_ROUTE = `${FILE_DROP_ROUTE}/resolve`;
var COPY_ROUTE = `${FILE_DROP_ROUTE}/copy`;
var CONFIG_ROUTE = `${FILE_DROP_ROUTE}/config`;
var SETTINGS_ROUTE = `${FILE_DROP_ROUTE}/settings`;
var SAMPLE_BYTES = 64 * 1024;
var SMALL_FILE_BYTES = 8 * 1024 * 1024;

// src/client/chooser.ts
function choosePath(name, candidates) {
  return new Promise((resolve) => {
    const backdrop = document.createElement("div");
    Object.assign(backdrop.style, {
      position: "fixed",
      inset: "0",
      zIndex: "2147483647",
      display: "grid",
      placeItems: "center",
      padding: "24px",
      background: "rgb(15 23 42 / 35%)"
    });
    const panel = document.createElement("div");
    Object.assign(panel.style, {
      width: "min(680px, 100%)",
      maxHeight: "min(560px, 80vh)",
      overflow: "auto",
      background: "#fff",
      color: "#0f172a",
      border: "1px solid #cbd5e1",
      borderRadius: "8px",
      boxShadow: "0 18px 48px rgb(15 23 42 / 28%)",
      padding: "20px",
      font: "14px/1.5 -apple-system, BlinkMacSystemFont, sans-serif"
    });
    const title = document.createElement("h2");
    title.textContent = `\u9009\u62E9 ${name} \u7684\u539F\u59CB\u8DEF\u5F84`;
    Object.assign(title.style, { margin: "0 0 14px", fontSize: "16px", letterSpacing: "0" });
    panel.append(title);
    const finish = (path) => {
      backdrop.remove();
      resolve(path);
    };
    for (const path of candidates) {
      const button = document.createElement("button");
      button.type = "button";
      button.textContent = path;
      Object.assign(button.style, {
        display: "block",
        width: "100%",
        margin: "8px 0",
        padding: "10px 12px",
        textAlign: "left",
        border: "1px solid #cbd5e1",
        borderRadius: "6px",
        background: "#f8fafc",
        color: "#0f172a",
        cursor: "pointer",
        overflowWrap: "anywhere",
        letterSpacing: "0"
      });
      button.addEventListener("click", () => {
        finish(path);
      });
      panel.append(button);
    }
    const cancel = document.createElement("button");
    cancel.type = "button";
    cancel.textContent = "\u53D6\u6D88";
    Object.assign(cancel.style, {
      marginTop: "10px",
      padding: "8px 12px",
      border: "1px solid #cbd5e1",
      borderRadius: "6px",
      background: "#fff",
      color: "#334155",
      cursor: "pointer",
      letterSpacing: "0"
    });
    cancel.addEventListener("click", () => {
      finish();
    });
    panel.append(cancel);
    backdrop.addEventListener("click", (event) => {
      if (event.target === backdrop) finish();
    });
    backdrop.append(panel);
    document.body.append(backdrop);
  });
}

// src/client/fingerprint.ts
function droppedFileMeta(file) {
  return { kind: "file", name: file.name, size: file.size, lastModified: file.lastModified };
}
function sampleRanges(size) {
  if (!Number.isSafeInteger(size) || size < 0) throw new TypeError("size must be a non-negative safe integer");
  if (size <= SAMPLE_BYTES * 3) return [{ start: 0, length: size }];
  return [
    0,
    Math.max(0, Math.floor(size / 2) - Math.floor(SAMPLE_BYTES / 2)),
    size - SAMPLE_BYTES
  ].map((start) => ({ start, length: Math.min(SAMPLE_BYTES, size - start) }));
}
async function hashFromFile(file, size, ranges) {
  const parts = [];
  for (const range of ranges) {
    parts.push(new Uint8Array(await file.slice(range.start, range.start + range.length).arrayBuffer()));
  }
  const header = new Uint8Array(8);
  new DataView(header.buffer).setBigUint64(0, BigInt(size), false);
  const total = header.length + parts.reduce((sum, part) => sum + part.length, 0);
  const joined = new Uint8Array(total);
  joined.set(header, 0);
  let offset = header.length;
  for (const part of parts) {
    joined.set(part, offset);
    offset += part.length;
  }
  const digest = await crypto.subtle.digest("SHA-256", joined);
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}
async function sampleFingerprint(file) {
  return hashFromFile(file, file.size, sampleRanges(file.size));
}
async function fullFingerprint(file) {
  return hashFromFile(file, file.size, [{ start: 0, length: file.size }]);
}

// src/client/locator.ts
async function request(body) {
  const response = await fetch(RESOLVE_ROUTE, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body)
  });
  const value = await response.json();
  return response.ok ? value : { status: "error", message: value.status === "error" ? value.message : `HTTP ${response.status}` };
}
function workspaceContext(workspaces, currentWorkspacePath) {
  return {
    workspacePaths: workspaces.list.getSnapshot().items.map((item) => item.path),
    ...currentWorkspacePath === void 0 ? {} : { currentWorkspacePath }
  };
}
async function locateDroppedFile(file, workspaces, currentWorkspacePath) {
  const meta = droppedFileMeta(file);
  let result = await request({ phase: "metadata", file: meta, ...workspaceContext(workspaces, currentWorkspacePath) });
  if (result.status !== "sample-required") return result;
  result = await request({ phase: "sample", file: meta, candidates: result.candidates, digest: await sampleFingerprint(file) });
  if (result.status !== "full-required") return result;
  return request({ phase: "full", file: meta, candidates: result.candidates, digest: await fullFingerprint(file) });
}

// src/client/paths.ts
function detectPathPlatform(navigatorValue = navigator) {
  const userAgentPlatform = navigatorValue.userAgentData?.platform;
  const platform = userAgentPlatform ?? navigatorValue.platform;
  return /win/i.test(platform) ? "windows" : "posix";
}
function pathFromFileUrl(url, platform) {
  if (url.protocol !== "file:") return void 0;
  const pathname = decodeURIComponent(url.pathname);
  if (!pathname.startsWith("/") || pathname === "/") return void 0;
  if (platform === "posix") {
    return url.host === "" || url.host === "localhost" ? pathname : void 0;
  }
  if (url.host !== "" && url.host !== "localhost") {
    return `\\\\${decodeURIComponent(url.host)}${pathname.replaceAll("/", "\\")}`;
  }
  const drivePath = /^\/([A-Za-z]:)(\/.*)$/.exec(pathname);
  if (drivePath === null) return void 0;
  return `${drivePath[1]}${drivePath[2].replaceAll("/", "\\")}`;
}
function pathsFromUriList(value, platform = detectPathPlatform()) {
  const paths = [];
  const seen = /* @__PURE__ */ new Set();
  for (const line of value.split(/\r?\n/)) {
    const candidate = line.trim();
    if (candidate === "" || candidate.startsWith("#")) continue;
    let url;
    try {
      url = new URL(candidate);
    } catch {
      continue;
    }
    const path = pathFromFileUrl(url, platform);
    if (path === void 0 || seen.has(path)) continue;
    seen.add(path);
    paths.push(path);
  }
  return paths;
}
function pathsFromDrop(dataTransfer, platform = detectPathPlatform()) {
  const uriList = dataTransfer.getData("text/uri-list");
  const uriPaths = pathsFromUriList(uriList, platform);
  if (uriPaths.length > 0) return uriPaths;
  const plain = dataTransfer.getData("text/plain");
  return pathsFromUriList(plain, platform);
}

// src/client/icons.ts
var FILE_ICONS = {
  pdf: '<path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5zM1.6 11.85H0v3.999h.791v-1.342h.803q.43 0 .732-.173.305-.175.463-.474a1.4 1.4 0 0 0 .161-.677q0-.375-.158-.677a1.2 1.2 0 0 0-.46-.477q-.3-.18-.732-.179m.545 1.333a.8.8 0 0 1-.085.38.57.57 0 0 1-.238.241.8.8 0 0 1-.375.082H.788V12.48h.66q.327 0 .512.181.185.183.185.522m1.217-1.333v3.999h1.46q.602 0 .998-.237a1.45 1.45 0 0 0 .595-.689q.196-.45.196-1.084 0-.63-.196-1.075a1.43 1.43 0 0 0-.589-.68q-.396-.234-1.005-.234zm.791.645h.563q.371 0 .609.152a.9.9 0 0 1 .354.454q.118.302.118.753a2.3 2.3 0 0 1-.068.592 1.1 1.1 0 0 1-.196.422.8.8 0 0 1-.334.252 1.3 1.3 0 0 1-.483.082h-.563zm3.743 1.763v1.591h-.79V11.85h2.548v.653H7.896v1.117h1.606v.638z"/>',
  doc: '<path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2v-1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5zm-7.839 9.166v.522q0 .384-.117.641a.86.86 0 0 1-.322.387.9.9 0 0 1-.469.126.9.9 0 0 1-.471-.126.87.87 0 0 1-.32-.386 1.55 1.55 0 0 1-.117-.642v-.522q0-.386.117-.641a.87.87 0 0 1 .32-.387.87.87 0 0 1 .471-.129q.264 0 .469.13a.86.86 0 0 1 .322.386q.117.255.117.641m.803.519v-.513q0-.565-.205-.972a1.46 1.46 0 0 0-.589-.63q-.381-.22-.917-.22-.533 0-.92.22a1.44 1.44 0 0 0-.589.627q-.204.406-.205.975v.513q0 .563.205.973.205.406.59.627.386.216.92.216.535 0 .916-.216.383-.22.59-.627.204-.41.204-.973M0 11.926v4h1.459q.603 0 .999-.238a1.45 1.45 0 0 0 .595-.689q.196-.45.196-1.084 0-.63-.196-1.075a1.43 1.43 0 0 0-.59-.68q-.395-.234-1.004-.234zm.791.645h.563q.371 0 .609.152a.9.9 0 0 1 .354.454q.118.302.118.753a2.3 2.3 0 0 1-.068.592 1.1 1.1 0 0 1-.196.422.8.8 0 0 1-.334.252 1.3 1.3 0 0 1-.483.082H.79V12.57Zm7.422.483a1.7 1.7 0 0 0-.103.633v.495q0 .369.103.627a.83.83 0 0 0 .298.393.85.85 0 0 0 .478.131.9.9 0 0 0 .401-.088.7.7 0 0 0 .273-.248.8.8 0 0 0 .117-.364h.765v.076a1.27 1.27 0 0 1-.226.674q-.205.29-.55.454a1.8 1.8 0 0 1-.786.164q-.54 0-.914-.216a1.4 1.4 0 0 1-.571-.627q-.194-.408-.194-.976v-.498q0-.568.197-.978.195-.411.571-.633.378-.223.911-.223.328 0 .607.097.28.093.489.272a1.33 1.33 0 0 1 .466.964v.073H9.78a.85.85 0 0 0-.12-.38.7.7 0 0 0-.273-.261.8.8 0 0 0-.398-.097.8.8 0 0 0-.475.138.87.87 0 0 0-.301.398"/>',
  xls: '<path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5zM6.472 15.29a1.2 1.2 0 0 1-.111-.449h.765a.58.58 0 0 0 .254.384q.106.073.25.114.143.041.319.041.246 0 .413-.07a.56.56 0 0 0 .255-.193.5.5 0 0 0 .085-.29.39.39 0 0 0-.153-.326q-.152-.12-.462-.193l-.619-.143a1.7 1.7 0 0 1-.539-.214 1 1 0 0 1-.351-.367 1.1 1.1 0 0 1-.123-.524q0-.366.19-.639.19-.272.527-.422.338-.15.777-.149.457 0 .78.152.324.153.5.41.18.255.2.566h-.75a.56.56 0 0 0-.12-.258.6.6 0 0 0-.247-.181.9.9 0 0 0-.369-.068q-.325 0-.513.152a.47.47 0 0 0-.184.384q0 .18.143.3a1 1 0 0 0 .405.175l.62.143q.326.075.566.211a1 1 0 0 1 .375.358q.135.222.135.56 0 .37-.188.656a1.2 1.2 0 0 1-.539.439q-.351.158-.858.158-.381 0-.665-.09a1.4 1.4 0 0 1-.478-.252 1.1 1.1 0 0 1-.29-.375m-2.945-3.358h-.893L1.81 13.37h-.036l-.832-1.438h-.93l1.227 1.983L0 15.931h.861l.853-1.415h.035l.85 1.415h.908L2.253 13.94zm2.727 3.325H4.557v-3.325h-.79v4h2.487z"/>',
  ppt: '<path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5zM1.6 11.85H0v3.999h.791v-1.342h.803q.43 0 .732-.173.305-.175.463-.474a1.4 1.4 0 0 0 .161-.677q0-.375-.158-.677a1.2 1.2 0 0 0-.46-.477q-.3-.18-.732-.179m.545 1.333a.8.8 0 0 1-.085.38.57.57 0 0 1-.238.241.8.8 0 0 1-.375.082H.788V12.48h.66q.327 0 .512.181.185.183.185.522m2.817-1.333h-1.6v3.999h.791v-1.342h.803q.43 0 .732-.173.305-.175.463-.474.162-.302.161-.677 0-.375-.158-.677a1.2 1.2 0 0 0-.46-.477q-.3-.18-.732-.179m.545 1.333a.8.8 0 0 1-.085.38.57.57 0 0 1-.238.241.8.8 0 0 1-.375.082H4.15V12.48h.66q.327 0 .512.181.185.183.185.522m2.767-.67v3.336H7.48v-3.337H6.346v-.662h3.065v.662z"/>',
  zip: '<path d="M5 7.5a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v.938l.4 1.599a1 1 0 0 1-.416 1.074l-.93.62a1 1 0 0 1-1.11 0l-.929-.62a1 1 0 0 1-.415-1.074L5 8.438zm2 0H6v.938a1 1 0 0 1-.03.243l-.4 1.598.93.62.929-.62-.4-1.598A1 1 0 0 1 7 8.438z"/><path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1h-2v1h-1v1h1v1h-1v1h1v1H6V5H5V4h1V3H5V2h1V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/>',
  vid: '<path d="M6 6.883v4.234a.5.5 0 0 0 .757.429l3.528-2.117a.5.5 0 0 0 0-.858L6.757 6.454a.5.5 0 0 0-.757.43z"/><path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2M9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>',
  aud: '<path d="M11 6.64a1 1 0 0 0-1.243-.97l-1 .25A1 1 0 0 0 8 6.89v4.306A2.6 2.6 0 0 0 7 11c-.5 0-.974.134-1.338.377-.36.24-.662.628-.662 1.123s.301.883.662 1.123c.364.243.839.377 1.338.377s.974-.134 1.338-.377c.36-.24.662-.628.662-1.123V8.89l2-.5z"/><path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2M9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>',
  code: '<path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/><path d="M8.646 6.646a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1 0 .708l-2 2a.5.5 0 0 1-.708-.708L10.293 9 8.646 7.354a.5.5 0 0 1 0-.708m-1.292 0a.5.5 0 0 0-.708 0l-2 2a.5.5 0 0 0 0 .708l2 2a.5.5 0 0 0 .708-.708L5.707 9l1.647-1.646a.5.5 0 0 0 0-.708"/>',
  text: '<path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/><path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>',
  file: '<path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/>'
};

// src/client/pills.ts
var fileQueue = [];
var onChange = null;
function setPillChangeListener(listener) {
  onChange = listener;
}
function changed() {
  renderPills();
  if (onChange) onChange();
  if (fileQueue.length > 0) document.body.setAttribute("data-dsh-drag-file-pills", "1");
  else document.body.removeAttribute("data-dsh-drag-file-pills");
}
function addPill(pill) {
  fileQueue.push(pill);
  changed();
}
function removePill(path) {
  const index = fileQueue.findIndex((item) => item.path === path);
  if (index >= 0) {
    fileQueue.splice(index, 1);
    changed();
  }
}
function clearPills() {
  fileQueue.length = 0;
  changed();
}
function fileKind(name) {
  const n = String(name || "").toLowerCase();
  const ext = (n.split(".").at(-1) ?? "").trim();
  if (ext === "pdf") return { icon: FILE_ICONS.pdf };
  if (/^docx?$/.test(ext)) return { icon: FILE_ICONS.doc };
  if (/^xlsx?$/.test(ext)) return { icon: FILE_ICONS.xls };
  if (/^pptx?$/.test(ext)) return { icon: FILE_ICONS.ppt };
  if (/^(zip|rar|7z|tar|gz)$/.test(ext)) return { icon: FILE_ICONS.zip };
  if (/^(mp4|mov|webm|mkv|avi)$/.test(ext)) return { icon: FILE_ICONS.vid };
  if (/^(mp3|wav|flac|m4a)$/.test(ext)) return { icon: FILE_ICONS.aud };
  if (/^(py|js|ts|tsx|jsx|go|rs|java|c|cpp|h|sh|ps1|sql)$/.test(ext)) return { icon: FILE_ICONS.code };
  if (/^(txt|md|csv|json|ndjson|log|yaml|yml|toml|xml|html|css)$/.test(ext)) return { icon: FILE_ICONS.text };
  if (ext.length > 0) return { ext: ext.toUpperCase().slice(0, 4) };
  return { icon: FILE_ICONS.file };
}
function fileIconElement(name, size = 20) {
  const kind = fileKind(name);
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", "0 0 16 16");
  svg.setAttribute("width", String(size));
  svg.setAttribute("height", String(size));
  svg.setAttribute("fill", "currentColor");
  svg.setAttribute("aria-hidden", "true");
  if (kind.icon) {
    svg.innerHTML = kind.icon;
    return svg;
  }
  svg.remove();
  const tile = document.createElement("span");
  tile.textContent = kind.ext ?? "";
  tile.style.cssText = "flex:none;min-width:24px;height:24px;padding:0 3px;box-sizing:border-box;display:grid;place-items:center;border-radius:5px;background:var(--dsw-alias-surface-raised, rgba(148,163,184,.14));color:var(--dsw-alias-fg-secondary, #94a3b8);font:700 8px/1 -apple-system, BlinkMacSystemFont, sans-serif;letter-spacing:.2px";
  return tile;
}
function formatSize(bytes) {
  if (!Number.isFinite(bytes) || bytes < 0) return "";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}
var PILLS_ATTR = "data-drag-file-pills";
function findComposer() {
  return document.querySelector("textarea");
}
function findRail() {
  return document.querySelector('[class*="_attachments"]');
}
function findCard(ta) {
  const scroll = ta.parentElement && ta.parentElement.parentElement;
  return scroll ? scroll.parentElement : null;
}
function renderPills() {
  const ta = findComposer();
  if (!ta) return;
  const old = document.querySelector(`[${PILLS_ATTR}]`);
  if (old) old.remove();
  if (fileQueue.length === 0) return;
  const bar = document.createElement("div");
  bar.setAttribute(PILLS_ATTR, "1");
  bar.style.cssText = "display:flex;gap:8px;flex-wrap:wrap;align-items:center;padding:2px 0";
  for (const item of fileQueue) {
    const pill = document.createElement("span");
    pill.style.cssText = "position:relative;display:inline-flex;align-items:center;gap:9px;box-sizing:border-box;max-width:340px;height:36px;padding:0 10px 0 8px;border:1px solid var(--dsw-alias-line-strong, rgba(148,163,184,.7));background:var(--dsw-alias-surface-raised, rgba(148,163,184,.14));border-radius:10px;overflow:hidden;transition:border-color .12s ease,background-color .12s ease";
    pill.addEventListener("mouseenter", () => {
      pill.style.borderColor = "var(--dsw-alias-line-solid, rgba(203,213,225,.9))";
      pill.style.background = "var(--dsw-alias-interactive-bg-hover, rgba(148,163,184,.22))";
    });
    pill.addEventListener("mouseleave", () => {
      pill.style.borderColor = "var(--dsw-alias-line-strong, rgba(148,163,184,.7))";
      pill.style.background = "var(--dsw-alias-surface-raised, rgba(148,163,184,.14))";
    });
    const tile = fileIconElement(item.name, 18);
    const name = document.createElement("span");
    name.textContent = item.name;
    name.title = item.name;
    name.style.cssText = "flex:0 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:13px/1.4 -apple-system, BlinkMacSystemFont, sans-serif;color:var(--dsw-alias-fg-primary, #e2e8f0)";
    const size = document.createElement("span");
    const formatted = formatSize(item.size);
    size.textContent = formatted;
    size.style.cssText = "flex:none;font:11px/1.4 -apple-system, BlinkMacSystemFont, sans-serif;color:var(--dsw-alias-fg-secondary, #cbd5e1)";
    const remove = document.createElement("button");
    remove.type = "button";
    remove.textContent = "\u2715";
    remove.title = "\u79FB\u9664\u9644\u4EF6";
    remove.style.cssText = "flex:none;width:18px;height:18px;display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:50%;cursor:pointer;background:rgba(0,0,0,.28);color:var(--dsw-alias-fg-secondary, #cbd5e1);font-size:10px;line-height:1;padding:0";
    remove.addEventListener("click", () => {
      removePill(item.path);
    });
    pill.append(tile, name, size, remove);
    bar.append(pill);
  }
  const rail = findRail();
  if (rail) {
    rail.appendChild(bar);
  } else {
    const card = findCard(ta);
    if (!card) return;
    const scroll = ta.parentElement?.parentElement;
    if (scroll) card.insertBefore(bar, scroll);
  }
}
var chipsTimer;
function ensurePillsObserver(ta) {
  const card = findCard(ta);
  if (!card) return () => {
  };
  const observer = new MutationObserver(() => {
    if (fileQueue.length > 0 && document.querySelector(`[${PILLS_ATTR}]`) === null) {
      if (chipsTimer !== void 0) clearTimeout(chipsTimer);
      chipsTimer = setTimeout(renderPills, 60);
    }
  });
  observer.observe(card, { childList: true, subtree: true });
  return () => observer.disconnect();
}
function injectRailStyle() {
  const style = document.createElement("style");
  style.id = "dsh-drag-file-style";
  style.textContent = '[class*="_attachments"]{display:flex;flex-wrap:wrap;align-items:center;gap:8px}';
  document.head.append(style);
  return () => style.remove();
}
function mountPillRail() {
  const ta = findComposer();
  const disposeObserver = ta ? ensurePillsObserver(ta) : () => {
  };
  renderPills();
  return disposeObserver;
}

// src/client/settings-section.tsx
var import_react = require("react");
var ROW = {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  gap: "16px",
  padding: "12px 0",
  borderBottom: "1px solid var(--dsw-alias-border-l2, rgba(148,163,184,.18))"
};
var LABEL = {
  minWidth: "0",
  color: "var(--dsw-alias-label-primary, #e2e8f0)",
  fontSize: "13px",
  fontWeight: "500",
  lineHeight: "1.5"
};
var HINT = {
  color: "var(--dsw-alias-label-tertiary, #94a3b8)",
  fontSize: "12px",
  lineHeight: "1.5",
  margin: "2px 0 0"
};
var INPUT = {
  border: "1px solid var(--dsw-alias-border-l2, rgba(148,163,184,.28))",
  background: "var(--dsw-alias-bg-layer-3, rgba(148,163,184,.08))",
  height: "34px",
  color: "var(--dsw-alias-label-primary, #e2e8f0)",
  borderRadius: "8px",
  padding: "0 12px",
  fontSize: "13px",
  lineHeight: "1.5",
  boxSizing: "border-box"
};
var SELECT = {
  ...INPUT,
  minWidth: "200px",
  cursor: "pointer"
};
var SAVE = {
  border: "1px solid transparent",
  borderRadius: "8px",
  padding: "5px 16px",
  fontSize: "13px",
  lineHeight: "1.5",
  cursor: "pointer",
  background: "var(--dsw-alias-button-info-fill, #3964fe)",
  color: "#fff"
};
var STATUS = {
  fontSize: "12px",
  lineHeight: "1.5",
  margin: "8px 0 0"
};
function DragFileSettingsSection() {
  const [config2, setConfig] = (0, import_react.useState)({ mode: "resolve", dropDir: ".drops" });
  const [saving, setSaving] = (0, import_react.useState)(false);
  const [status, setStatus] = (0, import_react.useState)(null);
  (0, import_react.useEffect)(() => {
    let alive = true;
    fetch("/file-drop/settings").then((response) => response.json()).then((result) => {
      if (!alive) return;
      if (result.ok && result.value) setConfig((prev) => ({ ...prev, ...result.value }));
    }).catch(() => {
    });
    return () => {
      alive = false;
    };
  }, []);
  const save = async () => {
    setSaving(true);
    setStatus(null);
    try {
      const response = await fetch("/file-drop/settings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(config2)
      });
      const result = await response.json();
      setStatus(result.ok ? { kind: "ok", text: "\u5DF2\u4FDD\u5B58\uFF0C\u91CD\u542F dsh web \u540E\u751F\u6548\u3002" } : { kind: "err", text: `\u4FDD\u5B58\u5931\u8D25\uFF1A${result.error?.message ?? "\u672A\u77E5\u9519\u8BEF"}` });
    } catch (error) {
      setStatus({ kind: "err", text: `\u4FDD\u5B58\u5931\u8D25\uFF1A${error instanceof Error ? error.message : String(error)}` });
    }
    setSaving(false);
  };
  return (0, import_react.createElement)(
    "div",
    { style: { maxWidth: "640px" } },
    // 拖拽模式
    (0, import_react.createElement)(
      "div",
      { style: ROW },
      (0, import_react.createElement)(
        "div",
        { style: { minWidth: "0" } },
        (0, import_react.createElement)("label", { style: LABEL }, "\u62D6\u62FD\u6A21\u5F0F"),
        (0, import_react.createElement)("p", { style: HINT }, "resolve\uFF1A\u53EA\u5F15\u7528\u539F\u59CB\u6587\u4EF6\u8DEF\u5F84\uFF0C\u4E0D\u590D\u5236\u6587\u4EF6\uFF1Bcopy\uFF1A\u677E\u624B\u5373\u628A\u6587\u4EF6\u590D\u5236\u8FDB\u5DE5\u4F5C\u533A\u76EE\u5F55\u3002")
      ),
      (0, import_react.createElement)(
        "select",
        {
          style: SELECT,
          value: config2.mode,
          onChange: (event) => setConfig({ ...config2, mode: event.target.value })
        },
        (0, import_react.createElement)("option", { value: "resolve" }, "resolve\uFF08\u4EC5\u5F15\u7528\u8DEF\u5F84\uFF09"),
        (0, import_react.createElement)("option", { value: "copy" }, "copy\uFF08\u590D\u5236\u5230\u5DE5\u4F5C\u533A\uFF09")
      )
    ),
    // 目标文件夹
    (0, import_react.createElement)(
      "div",
      { style: ROW },
      (0, import_react.createElement)(
        "div",
        { style: { minWidth: "0" } },
        (0, import_react.createElement)("label", { style: LABEL }, "\u590D\u5236\u76EE\u6807\u6587\u4EF6\u5939"),
        (0, import_react.createElement)("p", { style: HINT }, "copy \u6A21\u5F0F\u4E0B\uFF0C\u6587\u4EF6\u590D\u5236\u5230\u5DE5\u4F5C\u533A\u4E0B\u7684\u8FD9\u4E2A\u76F8\u5BF9\u76EE\u5F55\uFF08\u9ED8\u8BA4 .drops\uFF09\u3002")
      ),
      (0, import_react.createElement)("input", {
        style: { ...INPUT, width: "200px" },
        value: config2.dropDir,
        placeholder: ".drops",
        onChange: (event) => setConfig({ ...config2, dropDir: event.target.value })
      })
    ),
    // 保存
    (0, import_react.createElement)(
      "div",
      { style: { display: "flex", alignItems: "center", gap: "16px", padding: "14px 0 4px" } },
      (0, import_react.createElement)("button", { style: SAVE, disabled: saving, onClick: () => {
        void save();
      } }, saving ? "\u4FDD\u5B58\u4E2D\u2026" : "\u4FDD\u5B58"),
      status !== null ? (0, import_react.createElement)("span", {
        style: { ...STATUS, color: status.kind === "ok" ? "var(--dsw-alias-label-secondary, #94a3b8)" : "var(--dsw-alias-label-error, #f87171)" }
      }, status.text) : null
    )
  );
}

// src/client/index.ts
var inject = ["conversation", "sessions", "workspaces", "slots"];
var PATCH_MARK = "__dshDragFilePatched";
var OVERLAY_ID = "dsh-drag-file-overlay";
var SENTINEL = "\u2060";
var config = { mode: "resolve", dropDir: ".drops" };
async function loadConfig() {
  try {
    const response = await fetch(CONFIG_ROUTE);
    const result = await response.json();
    if (response.ok && result.ok && result.value) {
      config = { ...config, ...result.value };
    }
  } catch (error) {
    console.error("[dsh-drag-file] config load failed:", error);
  }
}
function isImageFile(file) {
  return !!file && typeof file.type === "string" && file.type.indexOf("image/") === 0;
}
function basenameOf(path) {
  const parts = path.split(/[\\/]/);
  return parts.at(-1) ?? path;
}
function currentWorkspace(sessions, sessionId) {
  try {
    const state = sessions?.list?.getSnapshot?.();
    if (!state) return void 0;
    const id = sessionId || state.current;
    if (!id) return void 0;
    const row = state.byId ? state.byId[id] : void 0;
    return row && typeof row.cwd === "string" && row.cwd.length > 0 ? row.cwd : void 0;
  } catch {
  }
  return void 0;
}
function toBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  const chunk = 32768;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}
async function copyFileToWorkspace(file, workspace) {
  const buffer = await file.arrayBuffer();
  const payload = { name: file.name, dataBase64: toBase64(buffer) };
  if (workspace && workspace.length > 0) payload.workspace = workspace;
  const response = await fetch(COPY_ROUTE, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });
  const result = await response.json();
  if (!response.ok || !result.ok) {
    throw new Error(result.error && result.error.message ? result.error.message : "copy failed");
  }
  const path = result.value && result.value.path;
  if (typeof path !== "string" || path.length === 0) throw new Error("copy returned no path");
  return path;
}
async function resolveFile(ctx, file, workspace, directPaths) {
  const direct = directPaths.filter((path) => basenameOf(path) === file.name);
  if (direct.length === 1) return direct[0];
  const result = await locateDroppedFile(file, ctx.workspaces, workspace);
  if (result.status === "found") return result.path;
  if (result.status === "choose") return choosePath(file.name, result.candidates);
  if (result.status === "error") throw new Error(result.message);
  return void 0;
}
function createOverlay() {
  const root = document.createElement("div");
  root.id = OVERLAY_ID;
  root.setAttribute("role", "status");
  root.setAttribute("aria-live", "polite");
  Object.assign(root.style, {
    position: "fixed",
    inset: "0",
    zIndex: "2147483647",
    display: "grid",
    placeItems: "center",
    padding: "24px",
    pointerEvents: "none",
    opacity: "0",
    visibility: "hidden",
    transition: "opacity 140ms ease, visibility 140ms ease",
    background: "rgb(15 23 42 / 44%)",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)"
  });
  const panel = document.createElement("div");
  Object.assign(panel.style, {
    display: "grid",
    justifyItems: "center",
    gap: "14px",
    minWidth: "260px",
    padding: "28px 36px",
    color: "#ffffff",
    font: "600 16px/1.4 -apple-system, BlinkMacSystemFont, sans-serif",
    letterSpacing: "0"
  });
  const label = document.createElement("span");
  panel.append(label);
  root.append(panel);
  document.body.append(root);
  return {
    setActive(active) {
      label.textContent = config.mode === "copy" ? "\u677E\u5F00\u9F20\u6807\u4EE5\u590D\u5236\u6587\u4EF6\u5230\u5DE5\u4F5C\u533A" : "\u677E\u5F00\u9F20\u6807\u4EE5\u5F15\u7528\u6587\u4EF6\u8DEF\u5F84";
      root.style.opacity = active ? "1" : "0";
      root.style.visibility = active ? "visible" : "hidden";
    },
    dispose() {
      root.remove();
    }
  };
}
function hasFilePayload(event) {
  const types = event.dataTransfer?.types ?? [];
  return types.includes("Files") || types.includes("text/uri-list");
}
function currentInput(ctx) {
  try {
    const sessionId = ctx.sessions.list.getSnapshot().current;
    if (sessionId === void 0) return void 0;
    const scope = ctx.sessions.scope(sessionId);
    const conversation = ctx.get("conversation");
    const input = scope !== void 0 && conversation !== void 0 ? conversation.input.for(scope) : void 0;
    return input;
  } catch {
    return void 0;
  }
}
function syncDraftSentinel(ctx) {
  try {
    const input = currentInput(ctx);
    if (!input) return;
    const draft = input.state.getSnapshot().draft;
    if (fileQueue.length > 0) {
      if (draft.trim() === "") input.setDraft(SENTINEL);
    } else if (draft === SENTINEL) {
      input.setDraft("");
    }
  } catch {
  }
}
function patchSendSession(conversation) {
  const proto = conversation?.constructor?.prototype;
  if (!proto || typeof proto.sendSession !== "function" || proto[PATCH_MARK]) return;
  proto[PATCH_MARK] = true;
  const original = proto.sendSession;
  proto.sendSession = async function(session, text, imageIds, mode, signal) {
    const filePaths = fileQueue.map((item) => item.path);
    if (filePaths.length === 0) return original.call(this, session, text, imageIds, mode, signal);
    const controller = this;
    const attachments = typeof controller.draftImages === "function" ? controller.draftImages(imageIds) : [];
    if (attachments.length !== (imageIds ?? []).length) {
      throw new Error("conversation.sendSession: one or more draft images are no longer available");
    }
    const cleanText = (text ?? "").replace(/\u2060/g, "");
    const refs = filePaths.map((path) => `@"${path}"`).join("\n");
    const fullText = cleanText.trim() === "" ? refs : `${refs}
${cleanText}`;
    const content = [
      ...typeof controller.serializeImages === "function" ? await controller.serializeImages(attachments.map((attachment) => attachment.file)) : [],
      { type: "text", text: fullText }
    ];
    const result = await session.prompt?.(content, mode, signal);
    if (!result?.ok) return { kind: "error" };
    if (typeof controller.releaseDraftImages === "function") controller.releaseDraftImages(attachments);
    clearPills();
    return { kind: "success" };
  };
}
function apply(ctx) {
  void loadConfig();
  let dragDepth = 0;
  const overlay = createOverlay();
  const onDragEnter = (event) => {
    if (!hasFilePayload(event)) return;
    dragDepth += 1;
    overlay.setActive(true);
  };
  const onDragOver = (event) => {
    if (!hasFilePayload(event)) return;
    event.preventDefault();
    if (event.dataTransfer !== null) event.dataTransfer.dropEffect = "copy";
    overlay.setActive(true);
  };
  const onDragLeave = (event) => {
    if (!hasFilePayload(event)) return;
    dragDepth = Math.max(0, dragDepth - 1);
    if (dragDepth === 0) overlay.setActive(false);
  };
  const onDrop = (event) => {
    if (!hasFilePayload(event)) return;
    const files = Array.prototype.slice.call(event.dataTransfer ? event.dataTransfer.files : []);
    const images = files.filter(isImageFile);
    const others = files.filter((file) => !isImageFile(file));
    if (others.length === 0) {
      dragDepth = 0;
      overlay.setActive(false);
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    dragDepth = 0;
    overlay.setActive(false);
    const directPaths = pathsFromDrop(event.dataTransfer);
    const workspace = currentWorkspace(ctx.sessions);
    const target = event.target;
    if (images.length > 0) {
      try {
        const dt = new DataTransfer();
        images.forEach((file) => dt.items.add(file));
        setTimeout(() => {
          try {
            target?.dispatchEvent(new DragEvent("drop", { bubbles: true, cancelable: true, dataTransfer: dt }));
          } catch (error) {
            console.error("[dsh-drag-file] image re-dispatch failed:", error);
          }
        }, 0);
      } catch (error) {
        console.error("[dsh-drag-file] image re-dispatch setup failed:", error);
      }
    }
    setTimeout(() => {
      try {
        window.dispatchEvent(new DragEvent("dragend"));
      } catch {
      }
    }, 0);
    for (const file of others) {
      const work = config.mode === "copy" ? copyFileToWorkspace(file, workspace) : resolveFile(ctx, file, workspace, directPaths);
      work.then((path) => {
        if (path !== void 0) addPill({ path, name: file.name, size: file.size });
      }).catch((error) => {
        console.error("[dsh-drag-file] file processing failed:", error);
      });
    }
  };
  window.addEventListener("dragenter", onDragEnter);
  window.addEventListener("dragover", onDragOver);
  window.addEventListener("dragleave", onDragLeave);
  window.addEventListener("drop", onDrop, true);
  const conversation = ctx.get("conversation");
  if (conversation) patchSendSession(conversation);
  const disposeRail = mountPillRail();
  const disposeStyle = injectRailStyle();
  setPillChangeListener(() => syncDraftSentinel(ctx));
  const onAddPillEvent = (event) => {
    const detail = event.detail;
    if (!detail || typeof detail.path !== "string" || typeof detail.name !== "string") return;
    addPill({ path: detail.path, name: detail.name, size: typeof detail.size === "number" ? detail.size : void 0 });
  };
  window.addEventListener("dsh-drag-file:add-pill", onAddPillEvent);
  window.__dshDragFileActive = true;
  let removeSettingsSection = () => {
  };
  try {
    removeSettingsSection = ctx.slots.inject("settings.section", () => ctx.slots.register({
      name: "settings.section",
      id: "drag-file",
      order: 100,
      label: () => "\u62D6\u62FD\u6587\u4EF6\u8BBE\u7F6E"
    }, DragFileSettingsSection));
  } catch (error) {
    console.warn("[dsh-drag-file] settings section registration failed:", error);
  }
  ctx.effect(() => () => {
    window.removeEventListener("dragenter", onDragEnter);
    window.removeEventListener("dragover", onDragOver);
    window.removeEventListener("dragleave", onDragLeave);
    window.removeEventListener("drop", onDrop, true);
    overlay.dispose();
    disposeRail();
    disposeStyle();
    setPillChangeListener(null);
    window.removeEventListener("dsh-drag-file:add-pill", onAddPillEvent);
    delete window.__dshDragFileActive;
    removeSettingsSection();
  }, "drag-file: client lifecycle");
}

    return module.exports;
  },
});
